export enum GamesConstantsEnum {
    AxieInfinity = 'smooth-love-potion',
    BattleHero = 'battle-hero',
    BombCrypto = 'bomber-coin',
    CoinToFish = 'coin-to-fish',
    CryptoCars = 'cryptocars',
    CryptoCarsWorld = 'crypto-cars-world',
    CryptoMines = 'cryptomines-eternal',
    CryptoPlanes = 'cryptoplanes',
    PlantVsUndead = 'plant-vs-undead-token',
    SpacePortUniverse = 'spaceport-universe',
    ThetanArena = 'thetan-arena',
    WanakaFarmWairere = 'wanaka-farm-wairere-token',
    WanakaFarm = 'wanaka-farm',
}